import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import ThemeWrapper from "./components/ThemeWrapper";
import Cursor from "./components/Cursor/index";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper>
          <Cursor />
          {children}
        </ThemeWrapper>
      </body>
    </html>
  );
}
